# Generated by Django 4.1.7 on 2023-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_teacher_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=0),
        ),
    ]
