# Generated by Django 4.1.7 on 2023-04-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='show_theme',
            field=models.BooleanField(default=True),
        ),
    ]
