# Generated by Django 4.1.7 on 2023-04-02 16:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_lecture_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
