# Generated by Django 4.1.7 on 2023-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_result_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
