# Generated by Django 4.1.7 on 2023-04-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_answer1_question_answer2_question_answer3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
